# .github/workflows/test.yml

# Workflow name
name: Test

on:
  push:
    branches:
      - '**'
        
env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_BATCH_ID: ${{ github.sha }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install
      
      # 👇 Run any tests prior to running eyes-storybook.
      # - name: Run tests
      #   run: yarn test

      - name: Run eyes-storybook (Applitools)
        run: npx eyes-storybook -c packages/storybook/.storybook

  test-notifications:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status 
        uses: wei/curl@v1.1.1
        with:
          args: -d "" -X POST https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ secrets.APPLITOOLS_API_KEY }}
